name: workflow

on: [push]

jobs:
  greeting_job:
    runs-on: ubuntu-latest
    env:
      CLIENT_URL: https://leaflet-map-iota.vercel.app/
      SERVER_URL: https://leafletmap-glmu.onrender.com/
      DB_URL: ${{secrets.DB_URL}}
    steps:
      - name: "Say Hello Mona it's Monday"
        env:
          VITE_SERVER_URL: https://leafletmap-glmu.onrender.com/
        run: echo "$CLIENT_URL $SERVER_URL $VITE_SERVER_URL $DB_URL"
      - name: 'Check out repository code'
        working-directory: root/client
        env:
          VITE_SERVER_URL: https://leafletmap-glmu.onrender.com/
        run: echo "$VITE_SERVER_URL"
  
  